config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "ask", to: "questions#ask"
  get "answer", to: "answers#answer"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def answer
    # raise
    # Code pour l'action ask
   @question = params[:question]
   @answer = if @question == 'I am going to work'
    'Great!'
    elsif @question&.end_with?('?')
    'Silly question, get dressed and go to work!'
    else
    "I don't care, get dressed and go to work!"
  end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
    # Code pour l'action ask
  
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/answer.html.erb
<div class="container coach-container">
  <h1 class="display-4">Stupid Coaching</h1>

  <p class="question">
    <%= @question %>
    <br>
    <span class="author">— You</span>
  </p>

  <div class="answer">
    <p><%= @answer %></p>
    <span class="author">— Your coach</span>
  </div>

  <p class="link">
    <%= link_to 'Ask a new question', ask_path, class: 'btn btn-primary' %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/ask.html.erb
<h1>hello
</h1>
<form action="/answer" method="get" data-turbo="false">
  <input type="text" name="question">
  <input type="submit" value="Ask!">
</form>